"""Smoke test: run the whole pipeline in dry-run and assert the artifacts.

No key or network needed. Run:  python -m pytest -q   (or  python tests/test_smoke.py)
"""
from __future__ import annotations

import asyncio
import tempfile
from pathlib import Path

from openpyxl import load_workbook

from scan import config, io_xlsx, pipeline

config.DRY_RUN = True

# Isolate: run in a temp dir so the smoke test never clobbers real run artifacts
# (work/, review/, out/ in the project are used by real CLI/app runs).
_base = Path(tempfile.mkdtemp(prefix="scan-smoke-"))
config.WORK_DIR = _base / "work"
config.ORGS_WORK = config.WORK_DIR / "orgs"
config.REVIEW_DIR = _base / "review"
config.OUT_DIR = _base / "out"
config.INPUT_DIR = _base / "input"
config.MANIFEST = config.WORK_DIR / "manifest.json"
config.ORG_SHEET = config.INPUT_DIR / "organizations.xlsx"
for _d in (config.ORGS_WORK, config.REVIEW_DIR, config.OUT_DIR, config.INPUT_DIR):
    _d.mkdir(parents=True, exist_ok=True)


def _reset() -> None:
    io_xlsx.write_sample_orgs()
    for f in config.ORGS_WORK.glob("*.jsonl"):
        f.unlink()
    if config.MANIFEST.exists():
        config.MANIFEST.unlink()


def test_full_dry_run() -> None:
    _reset()

    # stage 1: fan-out -> review files
    asyncio.run(pipeline.run_stage1())
    assert (config.REVIEW_DIR / "longlist.xlsx").exists()
    assert (config.REVIEW_DIR / "hunches.md").exists()
    assert (config.REVIEW_DIR / "open_questions.md").exists()
    kept = io_xlsx.read_kept_longlist()
    assert len(kept) >= 1

    # stage 2: themes + memo -> deliverables
    asyncio.run(pipeline.run_stage2())
    memo = config.OUT_DIR / "synthesis_memo.md"
    scorecard = config.OUT_DIR / "theme_scorecard.xlsx"
    imap = config.OUT_DIR / "innovation_map.xlsx"
    assert memo.exists() and scorecard.exists() and imap.exists()

    # guardrail held: no tool trace, no dashes in the memo
    text = memo.read_text(encoding="utf-8").lower()
    assert "claude" not in text and "—" not in text and "generated by" not in text

    # author stamped on the workbooks
    assert load_workbook(scorecard).properties.creator == "Kayode Adeniyi"

    # hard constraint: an existing theme is always deepen, never enter
    rows = list(load_workbook(scorecard).active.iter_rows(values_only=True))
    for r in rows[3:]:  # skip intro, blank, header
        standing, posture = r[1], r[6]
        if standing == "existing":
            assert posture == "deepen", f"existing theme not deepen: {r[0]}"


if __name__ == "__main__":
    test_full_dry_run()
    print("smoke test passed")
