"""Render the synthesis memo as a clean Word document in ACET house style:
Calibri, black, one-inch margins, headings and bullets, author set to Kayode
Adeniyi, and no tool name in the file properties.
"""
from __future__ import annotations

import os
import re
import zipfile
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.shared import Inches, Pt, RGBColor

AUTHOR = "Kayode Adeniyi"


def _black(font, size: int = 12) -> None:
    font.name = "Calibri"
    font.size = Pt(size)
    font.color.rgb = RGBColor(0, 0, 0)


def _runs(p, text: str) -> None:
    """Add text to a paragraph, honoring **bold** spans."""
    for part in re.split(r"(\*\*[^*]+\*\*)", text):
        if len(part) > 4 and part.startswith("**") and part.endswith("**"):
            r = p.add_run(part[2:-2]); r.bold = True; _black(r.font)
        elif part:
            r = p.add_run(part); _black(r.font)


def _scrub_props(path: Path) -> None:
    """Strip any tool name from the file properties (app.xml Application and the
    core.xml description, which python-docx stamps 'generated by python-docx')."""
    with zipfile.ZipFile(path) as z:
        names = z.namelist()
        data = {n: z.read(n) for n in names}
    app = data.get("docProps/app.xml", b"").decode("utf-8", "ignore")
    if "<Application>" in app:
        app = re.sub(r"<Application>.*?</Application>",
                     "<Application>Microsoft Office Word</Application>", app)
    data["docProps/app.xml"] = app.encode("utf-8")
    core = data.get("docProps/core.xml", b"").decode("utf-8", "ignore")
    core = re.sub(r"<dc:description>.*?</dc:description>", "<dc:description></dc:description>",
                  core, flags=re.S)
    data["docProps/core.xml"] = core.encode("utf-8")
    tmp = str(path) + ".tmp"
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as z:
        for n in names:
            z.writestr(n, data[n])
    os.replace(tmp, path)


def write_memo_docx(markdown: str, path) -> Path:
    path = Path(path)
    doc = Document()

    normal = doc.styles["Normal"]
    _black(normal.font)
    normal.paragraph_format.space_after = Pt(8)
    normal.paragraph_format.line_spacing = 1.15

    for lvl, size in ((1, 18), (2, 14), (3, 12)):
        h = doc.styles[f"Heading {lvl}"]
        h.font.bold = True; h.font.italic = False; _black(h.font, size)
        h.paragraph_format.space_before = Pt(12); h.paragraph_format.space_after = Pt(4)

    for sec in doc.sections:
        sec.top_margin = sec.bottom_margin = Inches(1)
        sec.left_margin = sec.right_margin = Inches(1)

    for line in markdown.splitlines():
        s = line.rstrip()
        if not s:
            continue
        if s.startswith("### "):
            _runs(doc.add_paragraph(style="Heading 3"), s[4:])
        elif s.startswith("## "):
            _runs(doc.add_paragraph(style="Heading 2"), s[3:])
        elif s.startswith("# "):
            _runs(doc.add_paragraph(style="Heading 1"), s[2:])
        elif re.match(r"^\d+\.\s", s):
            _runs(doc.add_paragraph(style="List Number"), re.sub(r"^\d+\.\s", "", s))
        elif s.startswith("- ") or s.startswith("* "):
            _runs(doc.add_paragraph(style="List Bullet"), s[2:])
        else:
            _runs(doc.add_paragraph(), s)

    cp = doc.core_properties
    cp.author = AUTHOR; cp.last_modified_by = AUTHOR; cp.title = "Synthesis memo"
    cp.comments = ""; cp.category = ""
    stamp = datetime(2026, 7, 20, 9, 0, 0)
    cp.created = stamp; cp.modified = stamp
    doc.save(path)
    _scrub_props(path)
    return path
