"""One policy layer over every output, driven by context/policy.md.

Two non-negotiables enforced in one place, not per-agent:
  1. primary-source-only: a row cannot read "verified" without a confirming
     quote; if it lacks one it is downgraded to partial.
  2. no tool or AI trace in any deliverable, cell, or prose.
Deterministic checks against a fixed policy, never against model-supplied args.
"""
from __future__ import annotations

import re
from typing import Any

# Tool and model identifiers, matched as plain substrings, they never occur in
# ordinary economic prose.
BANNED_IDENT = [
    "openpyxl", "python-docx", "claude", "anthropic", "gemini", "chatgpt", "openai",
    "web_search",
]
# AI-trace phrases, matched with word boundaries so ordinary economics stays clean:
# "the value generated by exports" and "as an aid to growth" must pass, while
# "generated by AI" and "as an AI" must not.
BANNED_PHRASE = [
    r"ai[- ]generated", r"generated by (an? )?a\.?i\.?\b", r"generated by (an? )?tool\b",
    r"generated by (an? )?(language |ml )?model\b", r"auto[- ]?generated",
    r"machine[- ]generated", r"\bas an a\.?i\.?\b", r"\bllm\b", r"\blanguage model\b",
    r"\bgpt\b", r"http\s*403", r"search snippet",
]
# competitor model names, matched with word boundaries
BANNED_MODEL = [r"\bdeepseek\b", r"\bcopilot\b", r"\bllama\b", r"\bmistral\b", r"\bgrok\b"]
# Retrieval-mechanics phrases to keep out of analyst prose (specific, so "exports
# blocked by tariffs" is safe while "the request was blocked" is not).
MECHANICS = [
    r"\bscraped\b", r"fetched the url", r"http error", r"paywall",
    r"(request|access|page|site|url) (was |were )?blocked", r"blocked by cloudflare",
]
# long-dash glyphs used as em-dash substitutes (not the ordinary hyphen-minus):
# em, en, horizontal bar, figure dash, minus sign
_DASHES = "—–―‒−"


def settle_row(row: dict[str, Any]) -> dict[str, Any]:
    """The consistency gate. A row may read verified only if the verifier
    supported the claim with a confirming quote; otherwise it drops to partial.
    Any failed audit check raises a flag for a human to look again."""
    v = row.get("verification", {}) or {}
    a = row.get("audit", {}) or {}
    reasons = []

    supported = bool(v.get("claim_supported")) and bool((v.get("confirming_quote") or "").strip())
    if v.get("status") == "verified" and not supported:
        v["status"] = "partial"
        v["note"] = (v.get("note", "") + " (held to partial: claim not directly supported)").strip()

    # policy-trust: the confirming quote was checked against the actual source
    grounded = row.get("quote_grounded")           # True / False / None (uncheckable)
    if grounded is False:
        reasons.append("confirming quote not found in the source")
        if v.get("status") == "verified":
            v["status"] = "partial"
            v["note"] = (v.get("note", "") + " (held to partial: quote not in source)").strip()
    # content relevance: the reading's own quotes were checked against the source
    if row.get("reading_grounded") is False:
        reasons.append("the reading's quotes were not found in the source")
        if v.get("status") == "verified":
            v["status"] = "partial"
            v["note"] = (v.get("note", "") + " (held to partial: reading not grounded in source)").strip()
    row["verification"] = v

    if a.get("verdict") == "flag":
        reasons.append(a.get("notes") or "audit flagged")
    if not a.get("quote_supports_claim", True):
        reasons.append("quote does not support the claim")
    if not a.get("source_is_primary", True):
        reasons.append("source is not primary")
    if a.get("score_matches_evidence") in ("overstated", "understated"):
        reasons.append(f"score {a['score_matches_evidence']} vs evidence")
    # note: the old "quotes not confirmed verbatim" flag was dropped, the deterministic
    # grounding check (quote_grounded) now does the real verbatim verification.
    if row.get("coerced_fields"):
        reasons.append("model returned invalid values, defaulted: " + ", ".join(row["coerced_fields"]))
    row["flagged"] = bool(reasons)
    row["flags"] = reasons
    return row


def scan_text(text: str) -> list[str]:
    """Return any policy violations found in a block of deliverable text. Tool and
    model names match as substrings; AI-trace and retrieval phrases match with word
    boundaries, so ordinary economic prose (value generated by a sector, exports
    blocked by tariffs) is never flagged."""
    hits: list[str] = []
    low = text.lower()
    for b in BANNED_IDENT:
        if b in low:
            hits.append(f"banned token: {b}")
    for pat in BANNED_PHRASE + BANNED_MODEL:
        m = re.search(pat, low)
        if m:
            hits.append(f"banned token: {m.group(0)}")
    for pat in MECHANICS:
        m = re.search(pat, low)
        if m:
            hits.append(f"retrieval mechanic: {m.group(0)}")
    if any(d in text for d in _DASHES):     # em, en, horizontal-bar, figure-dash, minus
        hits.append("dash: use commas or rewrite")
    return hits


def scrub(text: str) -> str:
    """Best-effort cleanup for house style: replace every long-dash glyph with a comma."""
    text = re.sub(rf"\s*[{_DASHES}]\s*", ", ", text)
    return text


def assert_clean(label: str, text: str) -> None:
    hits = scan_text(text)
    if hits:
        raise ValueError(f"policy violation in {label}: {'; '.join(hits)}")
