"""One policy layer over every output, driven by context/policy.md.

Two non-negotiables enforced in one place, not per-agent:
  1. primary-source-only: a row cannot read "verified" without a confirming
     quote; if it lacks one it is downgraded to partial.
  2. no tool or AI trace in any deliverable, cell, or prose.
Deterministic checks against a fixed policy, never against model-supplied args.
"""
from __future__ import annotations

import re
from typing import Any

# Tokens that must never appear in a deliverable (prose, cells, file props).
BANNED = [
    "openpyxl", "python-docx", "claude", "anthropic", "gemini", "gpt", "openai",
    "chatgpt", "llm", "ai-generated", "ai generated", "generated by", "as an ai",
    "language model", "http 403", "blocked", "search snippet", "web_search",
]
# Retrieval-mechanics words to keep out of analyst prose.
MECHANICS = ["scraped", "fetched the url", "http error", "paywall blocked"]


def settle_row(row: dict[str, Any]) -> dict[str, Any]:
    """The consistency gate. A row may read verified only if the verifier
    supported the claim with a confirming quote; otherwise it drops to partial.
    Any failed audit check raises a flag for a human to look again."""
    v = row.get("verification", {}) or {}
    a = row.get("audit", {}) or {}
    reasons = []

    supported = bool(v.get("claim_supported")) and bool((v.get("confirming_quote") or "").strip())
    if v.get("status") == "verified" and not supported:
        v["status"] = "partial"
        v["note"] = (v.get("note", "") + " (held to partial: claim not directly supported)").strip()

    # policy-trust: the confirming quote was checked against the actual source
    grounded = row.get("quote_grounded")           # True / False / None (uncheckable)
    if grounded is False:
        reasons.append("confirming quote not found in the source")
        if v.get("status") == "verified":
            v["status"] = "partial"
            v["note"] = (v.get("note", "") + " (held to partial: quote not in source)").strip()
    row["verification"] = v

    if a.get("verdict") == "flag":
        reasons.append(a.get("notes") or "audit flagged")
    if not a.get("quote_supports_claim", True):
        reasons.append("quote does not support the claim")
    if not a.get("source_is_primary", True):
        reasons.append("source is not primary")
    if a.get("score_matches_evidence") in ("overstated", "understated"):
        reasons.append(f"score {a['score_matches_evidence']} vs evidence")
    # note: the old "quotes not confirmed verbatim" flag was dropped, the deterministic
    # grounding check (quote_grounded) now does the real verbatim verification.
    if row.get("coerced_fields"):
        reasons.append("model returned invalid values, defaulted: " + ", ".join(row["coerced_fields"]))
    row["flagged"] = bool(reasons)
    row["flags"] = reasons
    return row


def scan_text(text: str) -> list[str]:
    """Return any policy violations found in a block of deliverable text."""
    hits: list[str] = []
    low = text.lower()
    for b in BANNED:
        if b in low:
            hits.append(f"banned token: {b}")
    for m in MECHANICS:
        if m in low:
            hits.append(f"retrieval mechanic: {m}")
    if "—" in text or "–" in text:
        hits.append("dash: use commas or rewrite")
    return hits


def scrub(text: str) -> str:
    """Best-effort cleanup for house style: strip em and en dashes."""
    text = re.sub(r"\s*[—–]\s*", ", ", text)
    return text


def assert_clean(label: str, text: str) -> None:
    hits = scan_text(text)
    if hits:
        raise ValueError(f"policy violation in {label}: {'; '.join(hits)}")
